global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Plano 1 — app metrics
  - job_name: soc-worker
    static_configs:
      - targets: ['worker:9108']

  - job_name: soc-collector
    static_configs:
      - targets: ['collector:9109']

  # Plano 2 — infrastructure
  - job_name: dcgm-exporter
    static_configs:
      - targets: ['dcgm-exporter:9400']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
